package com.todolist.exceptions.enums;

public enum ErrosEnum {
        NAO_PERMITIR_EXCLUIR, NAO_PERMITIR_ATUALIZAR, TAREFA_JA_EXISTENTE, NAO_PERMITIR_CRIAR, DATA_INVALIDA, TAREFA_NAO_ENCONTRADA
}
