# Spring
spring.sql.init.mode=always
server.error.include-exception=false

# Banco de dados
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://admin:wmETpYG72AiJKJFW9D06OMo2oLPa4WR0@dpg-coj3q6gl5elc73dh5cv0-a\
  .oregon-postgres.render.com/todolist_j8bi
spring.datasource.username=admin
spring.datasource.password=wmETpYG72AiJKJFW9D06OMo2oLPa4WR0

# Hibernate
spring.application.name=to-do-list
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.servlet.application-display-name=to-do-list

## WebServer (rota acess�vel para a API)
server.servlet.context-path = /api

