# Banco de dados
# spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://to-do-list.cxmmoamskpsd.us-east-2.rds.amazonaws.com/to_do_list
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresPlusDialect
spring.datasource.username=postgres
spring.datasource.password=stargatesg129


# Spring
# spring.application.name=to-do-list
# spring.sql.init.mode=always
# server.error.include-exception=false
# server.servlet.application-display-name=to-do-list

# Configura��es do Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Spring Security
