spring.application.name=to-do-list

# Banco de dados
spring.jpa.database-platform=POSTGRESQL
spring.datasource.url=spring.datasource.url=jdbc:postgresql://localhost:5432/to-do-list?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=root


# Spring

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false